# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Checkout Build Repository
        uses: actions/checkout@v4
        
      - name: Checkout External Repository (CFG Schemas)
        uses: actions/checkout@v4
        with:
          repository: 'dato1999/topics'
          path: 'external-schemas'
      - name: print tree
        run: tree
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
  
      - name: Initialize sbt Configuration
        run: |
          mkdir -p project
          echo 'name := "generated-schemas"' > build.sbt
          echo 'version := "1.0.'${{ github.run_number }}'"' >> build.sbt
          echo 'scalaVersion := "2.13.12"' >> build.sbt
          echo 'sbt.version=1.9.8' > project/build.properties
  
      - name: Install sbt CLI
        uses: sbt/setup-sbt@v1
  
      - name: Set up JDK and SBT
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
  
      - name: Generate Scala Code
        run: python generate_schemas.py
  
      - name: Compile and Package JAR
        run: sbtx package
